{
 "title": "ECG QC stats",
 "time": { "from": "2021-02-15T00:19:30.717Z", "to": "2021-02-15T00:19:41.843Z" },
 "templating": {
  "list": [
   {
    "name": "record",
    "label": "Record",
    "query": "select distinct record from noisy_info"
   },
   {
    "name": "model",
    "label": "ECG QC model",
    "query": "select distinct model_ecg_qc from noisy_info "
   },
   {
    "name": "pat",
    "label": "Patient (metrics)",
    "query": "select distinct patient from metrics order by patient asc"
   },
   {
    "name": "patecg",
    "label": "Patient (ECG)",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"patient\""
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"channel\""
   },
   {
    "name": "snr",
    "label": "SNR (dB)",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"snr\""
   },
   {
    "name": "modelecg",
    "label": "ECG QC model (ECG)",
    "query": "select distinct model_ecg_qc from metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Positive predictivity",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select patient, snr, positive_predictivity, model_ecg_qc from metrics where patient in ($pat) and model_ecg_qc in ($model) order by model_ecg_qc, patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Sensitivity",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select patient, snr, sensitivity, model_ecg_qc from metrics where patient in ($pat) and model_ecg_qc in ($model) order by model_ecg_qc, patient, snr asc\n"
    }
   ]
  },
  {
   "title": "F1-score",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select patient, snr, f1_score, model_ecg_qc from metrics where patient in ($pat) and model_ecg_qc in ($model) order by model_ecg_qc, patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Failure detection",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "select patient, snr, failure_detection, model_ecg_qc from metrics where patient in ($pat) and model_ecg_qc in ($model) order by model_ecg_qc, patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Noisy chunks detected",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select patient, snr, noisy_pourcent, model_ecg_qc from noisy_info where patient in ($pat) and model_ecg_qc in ($model) and chan='MLII' order by model_ecg_qc, patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Noise stats",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select nb_chunks, nb_noisy_chunks, noisy_pourcent from noisy_info where snr=$snr and chan='$channel' and patient='$patecg' and model_ecg_qc='$modelecg'"
    }
   ]
  },
  {
   "title": "Record stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select length_record, min_interval, max_interval, med_interval, noisy_percent from noisy_info where record='$record' and model_ecg_qc='$model'"
    }
   ]
  },
  {
   "title": "ECG + Detected QRS (Hamilton)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Amplitude (mV)" }
   ],
   "targets": [
    {
     "alias": "ECG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT amplitude FROM \"qrs\".\"autogen\".\"ECG\" where snr='$snr' and channel='$channel' and patient='$patecg' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}